# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qS-4jJQV9Pcq1GYcGd8vNdGAiOCDrvhr
"""

name = "NLP Lab"
hours =30
pi = 3.14
topics =["Tokenization","POS tagging","NER"]

if hours > 25:
    print("sufficent hours for learning python.")
else:
    print("Add more practice hours")
for topic in topics:
    print("Learning:", topic)
def greet(student_name):
    return "Welcome to " + student_name
print(greet("AI & NLP Lab"))

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab') # Added to fix the LookupError

text = "Natural Language Processing helps computers understand human language"

tokens = word_tokenize(text)

stop_words = set(stopwords.words('english'))
filtered_words = [word for word in tokens if word.lower() not in stop_words]

ps = PorterStemmer()
stemmed_words = [ps.stem(word) for word in filtered_words]

print("Original Text:", text)
print("Tokens:", tokens)
print("After Stopword Removal:", filtered_words)
print("After Stemming:", stemmed_words)

from collections import Counter
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt')

text = "NLP is easy and NLP is powerful"

words = word_tokenize(text.lower())

word_freq = Counter(words)

print(word_freq)